### ISSUE TITLE
Error: unable to locate asset entry in pubspec.yaml

### ISSUE THREAD

**Issue by georgikoemdzhiev** [cybdom/hotel_booking_ui#1]
I tried to build your app but it trows the error below:

```
Error: unable to locate asset entry in pubspec.yaml: "fonts/OpenSans-light.ttf".
Error building assets                                                   
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* Where:                                                                
Script '/home/user/Development/flutter_tools/gradle/flutter.gradle' line: 765

```

Am I missing something? Thanks

Note: I am running your app on Linux (Manajro)

**Comment by cybdom** [comment]
the issue was because Linux has a case sensitive file system, and in the pubspec.yaml I wrote: "fonts/OpenSans-light.ttf" whereas the actual font file name was "OpenSans-Light.ttf". Thank you.

**Comment by georgikoemdzhiev** [comment]
Thanks for fixing that, it didn't occur to me that it's because of the Linux file system.
